[package]
name = "gvizor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.30"
env_logger = "0.11"
log = "0.4"
wgpu = "0.20"
tokio = { version = "1.37", features = ["full"] }